.github/workflows/build-push.yml, .github/workflows/cleanup-pr-image.yml
Don't tag images by short sha. In case of a PR only use the PR number to tag the image. In addition clean-up cosign signatures before deleting the PR image on PR close event.
=> fix: pr image cleanup

.github/workflows/build-push.yml, README.md
This feature adds SBOM generation and publishing to the container in several places next to the already available in-toto attestation.
- As a release artifact
- As a workflow artifact
Additionally the dependency review action is used to review dependencies for license issues or vulnerabilities.
=> feat: publish and review SBOM

.github/workflows/prime-cache.yml
GitHub cache can re-use cached data from ancestor branches. This PR adds a Docker build for all supported platforms on main that primes the cache. This should speed-up builds on feature branches and on the merge queue.
=> ci: prime GitHub cache with Docker images built on main

.github/workflows/build-push.yml
Add annotations to the manifest file as-per https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#adding-a-description-to-multi-arch-images.
Adding annotations has several benefits:
- Dependabot can show more information on changes when updating dependencies https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#docker
- The packages overview has more detail
Adding annotations can be simplified when https://github.com/docker/build-push-action/pull/992 is merged.
=> chore: add annotations to manifest

.github/dependabot.yml, .github/workflows/update-dependencies.yml
Using the `deps` tag will trigger release-please on the main branch as per release-please documentation (https://github.com/googleapis/release-please#step-1-ensure-releasable-units-are-merged).
=> fix: make sure all dependency updates are releasable units

.github/dependabot.yml
Group together all minor and patch level updates of actions.
One PR will be created for all actions that need update when the semver level is minor or patch. All major updates will still get their own PR as they will more likely break or introduce new functionality.
=> ci(dependabot): group minor and patch updates for actions

.devcontainer/apt-requirements-base.json
bzip2 was used to extract the previous arm toolchain. The arm toolchain is now packed with xz.
=> feat: remove unused package bzip2

.devcontainer/Dockerfile, test/testsuite.bats
This PR enables default generation of a compilation database (compile_commands.json) that can be used by tools like clangd, clang-tidy and include-what-you-use to provide diagnostics.
=> feat: set CMAKE_EXPORT_COMPILE_COMMANDS to On

.devcontainer/devcontainer-metadata-vscode.json
The JSON property customizations.vscode.settings was rooted under customizations instead of under customizations.vscode. This PR fixes that mistake.
Fixes #317
=> fix: move customizations.vscode.settings to the correct level

.github/workflows/linting-formatting.yml, .github/workflows/release-please.yml, .github/workflows/update-dependencies.yml
This PR switches from using a PAT (personal access token) to a token that is derived from an Org. wide app.
=> ci: use app-token-action for release and dependency updates

.devcontainer/cpp/test/testsuite.bats, .devcontainer/rust/Dockerfile, .devcontainer/rust/apt-requirements-base.json, .devcontainer/rust/test/testsuite.bats, .github/workflows/issue-creation-tool-versions.yml
This PR reworks the rust installation for Ubuntu 24.04. Several changes are included:
- rustup is installed via apt, as it is now part of the 24.04 packages
- rust is installed with the minimal profile, excluding docs, reducing image size with 700M
- additional rust tools are installed with cargo-binstall, removing the need for compilation from source
=> chore: rework rust installation

.github/workflows/update-dependencies.yml
Swap the content and note in the PR body to prevent the note from falling-off because of overflow of summary text.
Swap the content and note in the PR body to prevent the note from falling-off because of overflow of summary text.
=> docs: move manual test note on top when updating extensions

.github/workflows/build-push.yml, .github/workflows/ci.yml, .github/workflows/prime-cache.yml
Since the introduction of multiple container flavors built from a ci matrix build, the scope property should be used to prevent overwriting of the Docker layer cache.
See: https://stackoverflow.com/questions/76227392/github-build-push-action-and-gha-cache-should-i-set-the-github-ref-name-in-the and https://docs.docker.com/build/cache/backends/gha/#scope.
=> ci: add scope to GitHub Actions Docker build cache

.github/workflows/release-published.yml
Add a comment to all PRs that are contained in a specific release.
=> ci: add traceability from PR towards release

.github/workflows/release-please.yml, .github/workflows/update-dependencies.yml
As of philips-software/app-token-action#360 the philips-software/app-token-action is deprecated in favor of actions/create-github-app-token. This change replaces the usage of the former action by the latter.
=> ci: replace philips-software/app-token-action by actions/create-github-app-token

README.md
This PR adds the [OpenSSF best practices badge](https://www.bestpractices.dev/en) for this project.
=> docs: add OpenSSF best practices badge

.devcontainer/cpp/test/clang-cl/main.cpp
This PR adds several Windows SDK headers to the Windows cross compilation test with clang-cl. Making sure that the SDK is touched when doing the compilation.
=> test: add windows headers to clang-cl regression test

.devcontainer/cpp/devcontainer-lock.json, .devcontainer/cpp/devcontainer.json, .github/dependabot.yml, .github/workflows/update-dependencies.yml
This PR fixes automatic updates by Dependabot for devcontainer features. It corrects the directory in dependabot.yml and adds a lockfile for the features.
It also reduces the frequency of apt and vs code extension updates to weekly.
=> ci: fix devcontainer feature updates by dependabot

.devcontainer/cpp/test/test/CMakeLists.txt
This PR updates Googletest used in the tests to version 1.15.2.
=> test: update googletest to the latest released version

.devcontainer/rust/apt-requirements-base.json
=> feat: add udev to amp-devcontainer-rust

.github/workflows/acceptance-test.yml, test/cpp/features/pages/codespace.pom.ts, test/cpp/features/steps/codespace.steps.ts
This PR solves a few issues that reduce the flakiness of acceptance tests. The most apparent one being waiting on the Codespace to be started before running the tests.
=> test: reduce acceptance test flakiness

.devcontainer/cpp/Dockerfile, .devcontainer/cpp/apt-requirements-base.json, .devcontainer/rust/Dockerfile, .devcontainer/rust/apt-requirements-base.json, test/cpp/workspace/CMakeLists.txt
This PR includes an update to the GCC and ARM GCC toolchain to version 14.2.
See [this](https://gcc.gnu.org/gcc-14/changes.html) page for an overview of changes. Or [this](https://www.meetingcpp.com/blog/items/What-brings-an-upgrade-to-GCC-14-from-GCC-13-.html) page for an overview from a user's perspective.
=> feat: update GCC toolchain to version 14.2

.github/workflows/build-push.yml, .github/workflows/package-published.yml, .github/workflows/pr-image-cleanup.yml, .github/workflows/social-interaction.yml, README.md
This PR changes the way the amp-devcontainer images are signed. It moves away from using Cosign and Sigstore directly, instead [attest-build-provenance](https://github.com/actions/attest-build-provenance) is used.
=> chore: switch to GitHub attestations

.devcontainer/cpp/apt-requirements-base.json, .devcontainer/rust/Dockerfile, .devcontainer/rust/apt-requirements-base.json, test/rust/integration-tests.bats
This PR brings the Rust ecosystem up to date.
Update Rust to v1.84.0
Update cargo-binstal to v1.10.22
Update cargo-mutants to v25.0.0
Update flip-link to v0.1.10
Update probe-rs-tools to v0.26.0
=> feat: update Rust ecosystem to v1.84.0

.github/workflows/package-published.yml, .github/workflows/prime-cache.yml
Running the emulated arm64 build causes a segfault on Ubuntu 24.04 at the moment. This PR switches the default runner (based on Ubuntu 24.04) back to the previous version for the prime cache workflow.
=> ci: run prime-docker-cache on ubuntu-22.04

.github/RELEASE_TEMPLATE.md, .github/workflows/build-push.yml, .github/workflows/release-please.yml
Previously, when a new version was released, manual effort was required to fill in package details in the release notes.
This PR adds functionality to automatically:
- Fill in version and sha details of the published packages in the release notes
- Add SLSA provenance artifacts to the release
=> ci: automatically update release notes with image details

.github/workflows/build-push.yml, .github/workflows/release-please.yml, test/cpp/features/steps/fixtures.ts, test/cpp/integration-tests.bats
Using the GitHub cli (gh) needs a cloned repository (.git folder), in the release-please workflow it is thus necessary to use the actions/checkout step.
=> ci: fix automated release notes update

.github/workflows/release-please.yml
This PR fixes the release note generation by specifying the correct path to the template.
=> ci: fix release template generation (again)

test/cpp/workspace/clang-cl/toolchain.cmake, test/cpp/workspace/fuzzing/main.cpp
On arm64 hosts lld-link seems to default to /machine:ARM64 which is incorrect for the cross-compile use-case. Set the machine type to x64.
=> test: fix toolchain for arm64 hosts

.devcontainer/cpp/Dockerfile, .github/workflows/ci.yml, CMakeLists.txt, test/cpp/integration-tests.bats, test/cpp/workspace/test/CMakeLists.txt
Adding gcc and g++ alternatives pointing to the correct version of gcc prevents overwriting gcc and g++ by installers of the test environment. In the process switch to --slave options for g++/c++.
Added test that checks for consistent versions corresponding with the requested version from the json version file.
=> feat: add alternatives for gcc and g++

.github/workflows/issue-cleanup.yml, .github/workflows/issue-creation-tool-versions.yml, .github/workflows/linting-formatting.yml, .github/workflows/ossf-scorecard.yml, .github/workflows/pr-conventional-title.yml, .github/workflows/pr-image-cleanup.yml, .github/workflows/pr-report.yml, .github/workflows/release-build.yml, .github/workflows/release-please.yml, .github/workflows/release-published.yml, .github/workflows/social-interaction.yml, .github/workflows/update-dependencies.yml, .github/workflows/wc-acceptance-test.yml, .github/workflows/wc-build-push-test.yml, .github/workflows/wc-build-push.yml, .github/workflows/wc-integration-test.yml
This PR enables `disable-sudo` and `disable-sudo-and-containers` where possible. And it enables the `block` policy on jobs that have a stable baseline.
> [!NOTE]
> We are aware that step-security/harden-runner currently does not work on ARM runners and on job that themselves run in containers (via `container:`). We have purposely not excluded the step from those jobs, as support might come in the future.
=> ci: enable more harden-runner features

.github/workflows/image-cleanup.yml, .github/workflows/pr-image-cleanup.yml
This PR implements a better cleanup strategy for container images by replacing the existing bots-house/ghcr-delete-image-action with dataaxiom/ghcr-cleanup-action and adding a new scheduled workflow for general image cleanup.
From now on a regular cron job will run, next to the already present PR image cleanup, to remove orphaned and untagged images. This means all images that are not part of a parent with a tag will be removed. Including multi-arch images and attestations and signatures.
=> feat: implement better clean up strategy
